version: '3.8'
services:
  web:
    build:
      context: ./Service/MealPlanner
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - react-app
  react-app:
    build:
      context: ./Client
      dockerfile: Dockerfile
    volumes:
      - ./Client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
