// <auto-generated />
using System;
using System.Collections.Generic;
using MealPlanner.Api.Data;
using MealPlanner.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Api.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260430163919_AddRecipeCatalogue")]
    partial class AddRecipeCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueRecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<List<IngredientData>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("PublishedAt");

                    b.ToTable("catalogue_recipes", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueRecipeTagEntity", b =>
                {
                    b.Property<Guid>("CatalogueRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("CatalogueRecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("catalogue_recipe_tags", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("catalogue_tags", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.FriendAutoSharePreferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoShareGroceryLists")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoShareMealPlans")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FriendUserId")
                        .IsUnique();

                    b.ToTable("friend_auto_share_preferences", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.FriendRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequesterUserId", "RecipientUserId")
                        .IsUnique();

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.FriendshipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserBId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique();

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.GoogleIntegrationConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("GoogleEmail")
                        .HasColumnType("text");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject", "Provider")
                        .IsUnique();

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("google_integration_connections", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.GroceryListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<GroceryListItemData>>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<GroceryListItemData>>("PantryStapleItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("grocery_lists", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.GroceryListExportLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroceryListId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastExportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncHash")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GroceryListId", "Provider")
                        .IsUnique();

                    b.HasIndex("UserId", "WeekStart", "Provider")
                        .IsUnique();

                    b.ToTable("grocery_list_export_links", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.GroceryListShareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DismissedByRecipient")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedWithUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "SharedWithUserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("grocery_list_shares", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.MealPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<DayPlanData>>("Days")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.MealPlanShareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DismissedByRecipient")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedWithUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "SharedWithUserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("meal_plan_shares", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CatalogueRecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<IngredientData>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CatalogueRecipeId")
                        .IsUnique()
                        .HasFilter("\"CatalogueRecipeId\" IS NOT NULL");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueRecipeTagEntity", b =>
                {
                    b.HasOne("MealPlanner.Api.Data.Entities.CatalogueRecipeEntity", "CatalogueRecipe")
                        .WithMany("Tags")
                        .HasForeignKey("CatalogueRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Data.Entities.CatalogueTagEntity", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogueRecipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueRecipeEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MealPlanner.Api.Data.Entities.CatalogueTagEntity", b =>
                {
                    b.Navigation("RecipeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
